package org.shirabox.app.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF824790)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFCD7FF)
val light_onPrimaryContainer = Color(0xFF340043)
val light_secondary = Color(0xFF6A596C)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFF3DBF2)
val light_onSecondaryContainer = Color(0xFF241727)
val light_tertiary = Color(0xFF704D9F)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFEDDCFF)
val light_onTertiaryContainer = Color(0xFF290055)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF1E1B1E)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1E1B1E)
val light_surfaceVariant = Color(0xFFECDFE9)
val light_onSurfaceVariant = Color(0xFF4C444C)
val light_outline = Color(0xFF7E747D)
val light_inverseOnSurface = Color(0xFFF7EEF3)
val light_inverseSurface = Color(0xFF332F33)
val light_inversePrimary = Color(0xFFF2AFFF)
val light_surfaceTint = Color(0xFF824790)
val light_outlineVariant = Color(0xFFCFC3CD)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFF2AFFF)
val dark_onPrimary = Color(0xFF4E155E)
val dark_primaryContainer = Color(0xFF682F77)
val dark_onPrimaryContainer = Color(0xFFFCD7FF)
val dark_secondary = Color(0xFFD6C0D6)
val dark_onSecondary = Color(0xFF3A2B3C)
val dark_secondaryContainer = Color(0xFF524154)
val dark_onSecondaryContainer = Color(0xFFF3DBF2)
val dark_tertiary = Color(0xFFD8B9FF)
val dark_onTertiary = Color(0xFF401B6D)
val dark_tertiaryContainer = Color(0xFF583486)
val dark_onTertiaryContainer = Color(0xFFEDDCFF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1E1B1E)
val dark_onBackground = Color(0xFFE8E0E5)
val dark_surface = Color(0xFF1E1B1E)
val dark_onSurface = Color(0xFFE8E0E5)
val dark_surfaceVariant = Color(0xFF4C444C)
val dark_onSurfaceVariant = Color(0xFFCFC3CD)
val dark_outline = Color(0xFF988E97)
val dark_inverseOnSurface = Color(0xFF1E1B1E)
val dark_inverseSurface = Color(0xFFE8E0E5)
val dark_inversePrimary = Color(0xFF824790)
val dark_surfaceTint = Color(0xFFF2AFFF)
val dark_outlineVariant = Color(0xFF4C444C)
val dark_scrim = Color(0xFF000000)

val mangaPrimary = Color(0xFFF45236)
val ranobePrimary = Color(0xFF2E7EE6)